### ISSUE TITLE
v2023.06.0 Release

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJAPerf#344]
Items to address before the release:

- [x] Update GitLab CI so that it runs on ruby. This https://github.com/LLNL/RAJAPerf/pull/347 + follow-on PRs as needed.
- [x] Update RAJA, includes multiple PRs
  - [x] Update RAJA to v2023.06.1 release
  - [x] Make GitLab CI jobs consistent with RAJA, including:
    - [x] Switch GitLab CI to service user account
    - [x] Add +omptask build variant where appropriate
- [x] Merge Copy8 kernel: https://github.com/LLNL/RAJAPerf/pull/337
- [x] Merge Zonal Accumulation kernel: https://github.com/LLNL/RAJAPerf/pull/336
- [x] Merge FEM mass matrix assembly kernel: https://github.com/LLNL/RAJAPerf/pull/330
- [x] Merge EDGE3D kernel: https://github.com/LLNL/RAJAPerf/pull/300
- [x] Merge macro spelling fix: https://github.com/LLNL/RAJAPerf/pull/345
- [x] Merge tunings command line option: https://github.com/LLNL/RAJAPerf/pull/335
- [x] Merge Caliper Integration: https://github.com/LLNL/RAJAPerf/pull/352
- [ ] Merge MPI halo exchange: https://github.com/LLNL/RAJAPerf/pull/332
   -- note: we need to add MPI builds to CI checks
- [x] Merge kernel that captures array and length: https://github.com/LLNL/RAJAPerf/pull/258
- [x] Change loop_exec policies to seq_exec: https://github.com/LLNL/RAJAPerf/issues/341
- [x] Convert GPU exec to use new policies: https://github.com/LLNL/RAJAPerf/issues/342
- [x] mat-mat shared checksum issue: https://github.com/LLNL/RAJAPerf/issues/325
- [x] https://github.com/LLNL/RAJAPerf/issues/312
- [ ] Dispatch policies for halo exchange: https://github.com/LLNL/RAJAPerf/pull/260
- [x] Same GPU stream for all kernels: https://github.com/LLNL/RAJAPerf/pull/296

Others???
- [ ] script to make sweep graphs: https://github.com/LLNL/RAJAPerf/pull/245
- [ ] HIP MFMA checks: https://github.com/LLNL/RAJAPerf/pull/246 (need to fill out other back-ends?)
- [ ] Unsafe atomic tunings for HIP: https://github.com/LLNL/RAJAPerf/pull/247

**Comment by rhornung67** [comment]
Release is done
